sudo: required
language: node_js
node_js:
  - 0.10

before_install:
  - "npm install spacejam"
  - "curl https://install.meteor.com | /bin/sh"

script:
  - "node_modules/.bin/spacejam test-packages ./"
